#!/usr/bin/env python2

"""Quido ROS node

Usage:
  quido_node [options]

Options:
  -h, --help
  --debug
  --eth ADDR
  --usb DEV
"""

import rospy
import sys
from docopt import docopt
from papouch import Quido
from papouch_ros.srv import WriteIO, WriteIOResponse
import logging

NODE_NAME = "quido_node"

class QuidoNode(object):

    def __init__(self, quido):
        self.quido = quido
        self.srv = rospy.Service('~/write_io', WriteIO, self.write_io_cb)

    def write_io_cb(self, req):

        for i,s in zip(req.channel, req.state):
            self.quido.set_output(i, s)

        return True


def main():

    # debug
    logging.basicConfig (level='DEBUG' if opt['--debug'] else 'INFO')
    if opt['--debug']:
        rospy.loginfo("Params: \n%s", str(opt))

    # initialize ros node
    rospy.init_node(NODE_NAME)

    # ROS params

    # initialize quido class
    quido = Quido()
    if "--usb" in opt and opt['--usb']:
        rospy.loginfo("Connecting to Quido USB on %s", opt['--usb'])
        quido.connect_usb(opt['--usb'])
    elif "--eth" in opt and opt['--eth']:
        rospy.loginfo("Connecting to Quido ETH on %s", opt['--eth'])
        quido.connect_tcp(opt['--eth'])
    else:
        rospy.logwarn("You must specifi either --usb or --eth")
        sys.exit(1)

    # initialize quido node
    node = QuidoNode(quido)

    # spin ros node
    rospy.spin()

    # properly exit
    sys.exit(0)
    return


if __name__ == "__main__":
    # command line arguments
    opt = docopt(__doc__, argv=rospy.myargv()[1:])

    main()
