#!/usr/bin/env python2

"""
"""

import rospy
import sys
from papouch_ros.srv import WriteIO, WriteIORequest
from control_msgs.msg import GripperCommandAction, GripperCommandFeedback, GripperCommandResult
from sensor_msgs.msg import JointState
from std_srvs.srv import SetBool, SetBoolResponse


NODE_NAME = "schunk_gripper_node"
time_between_commands = 1
time_of_motion = 1


class SchunkGripperException(Exception):

    def __init__(self, msg=''):
        self.msg = msg

    def __str__(self):
        return "SchunkGripperException: " + msg


class SchunkGripperNode(object):
    """Class for Quido based Schunk gripper"""

    def __init__(self):

        # get parameters from the parameter server
        self.dummy_mode = bool(rospy.get_param('~dummy_mode', False))
        self.write_io_srv = str(rospy.get_param('write_io_srv', '/write_io'))
        self.close_io = int(rospy.get_param('~close_io', 1))
        self.open_io = int(rospy.get_param('~open_io', 2))
        self.stay_energized = bool(rospy.get_param('~stay_energized', False))
        self.action_name = str(rospy.get_param('action_name', 'gripper_action'))
        self.joint_name = str(rospy.get_param('joint_name', 'gripper_joint'))
        self.joint_limit = [0, float(rospy.get_param('joint_limit', 0.04))]
        self.joint_state = float(rospy.get_param('joint_state', 0.0))
        self.joint_state_rate = rospy.Rate(int(rospy.get_param('joint_state_rate', 10)))
        self.last_cmd_stamp = rospy.get_time()

        # message prototype
        self.joint_state_msg = JointState()
        self.joint_state_msg.header.frame_id = ''
        self.joint_state_msg.name = [self.joint_name]
        self.joint_state_msg.position = [self.joint_state]

        # action server for the gripper
        self.action_server = actionlib.SimpleActionServer(self.action_name, GripperCommandAction, execute_cb=self.action_execute_cb, auto_start=False)

        # publish joint states
        self.joint_state_pub = rospy.Publisher('joint_states', sensor_msgs.msg.JointState, queue_size = 50)

        # service to change the stay energized flag
        self.stay_energized_srv = rospy.Service('set_stay_energized', SetBool, self.set_stay_energized_cb)

        # create service proxy
        if not self.dummy_mode:
            try:
                rospy.wait_for_service(self.write_io_srv, 5)
            except rospy.ServiceException as e:
                raise SchunkGripperException('Timeout when waiting for service ' + self.write_io_srv)
            self.write_io_proxy = rospy.ServiceProxy(self.write_io_srv, WriteIO)

    def set_stay_energized_cb(self, req):
        """Callback function for set_stay_energized service."""

        # copy flag from request
        self.stay_energized = req.data

        # unenergize the gripper if stay_energized is false
        self.write_io(False, False)

        # return response
        return SetBoolResponse(success=True)

    def action_execute_cb(self, goal):
        """Callback function for gripper comand action."""

        # copy goal position from message
        goal_position = goal.command.position

        try:

            # unenergize the gipper
            self.write_io(False, False)

            # convert linear position to discreate state
            if goal_position > self.joint_limit[1]/2:
                goal_position = self.joint_limit[1]
                self.write_io(True, False)
            else:
                goal_position = self.joint_limit[0]
                self.write_io(False, True)

            # wait for gripper to finish its movement
            rospy.sleep(time_of_motion)

            # unenergize the gripper if stay_energized is fasle
            if not self.stay_energized:
                self.write_io(False, False)

            # set joint state
            self.joint_state = goal_position

        except SchunkGripperException as e:
            rospy.logerr(str(e))

        result = GripperCommandResult()
        result.position = self.joint_state
        self.action_server.set_succeeded(result)

    def write_io(self, open_sig_state, close_sig_state):
        # sleep between commands if this command is too soon
        if self.last_cmd_stamp - rospy.get_time() < time_between_commands:
            rospy.sleep(time_between_commands - (self.last_cmd_stamp - rospy.get_time()))

        # call service if not in dummy mode
        if not self.dummy_mode:
            req = WriteIORequest()
            req.channel = [self.open_io, self.close_io]
            req.state = [int(open_sig_state), int(close_sig_state)]

            try:
                # call quido service
                ret = self.write_io_proxy(req)

                # check output
                assert ret.retval == True
            except AssertError as e:
                raise SchunkGripperException("Failed to set quido output!")

        # store the stamp of this command
        self.last_cmd_stamp = rospy.get_time()

    def loop(self):
        rate = rospy.Rate(self.joint_state_rate)
        while not rospy.is_shutdown():
            # update time stamp
            self.joint_state_msg.header.stamp = rospy.get_ros_time()

            # update position
            self.joint_state_msg.position = [self.joint_state]

            # publish message
            self.joint_state_pub.publish(self.joint_state_msg)
            rate.sleep()

        # unenergize the gripper when shutdown
        self.write_io(False, False)


def main():
    rospy.init_node(NODE_NAME)
    node = SchunkGripperNode()
    node.loop()


if __name__ == "__main__":
    main()
